GET         http://localhost:5000/api/categories


###
POST   http://localhost:5000/api/products/create
Content-Type: application/json

{
   "name": "choco lava" ,
       "image": "imageURL" ,
       "price": 50 ,
       "cat_name" :"bakery" ,
       "description" : "soft" ,
      "priceDetails" : "{\"size\": 1, \"price\":50}",
        "subcat_name" : "cakes",
        "avgRating" : 0,
        "krRating" : 0,
        "totalReviews" : 0,
        "reviews" : "[]"
}

###

GET http://localhost:5000/api/search/ la 

###
PATCH  http://localhost:5000/api/reviews
Content-Type: application/json

{
   "id" : "0dda89a1-b565-40a3-8218-e5506b00d587",
   "productId": "1a700140-c298-4f80-8097-3cc972aedfcf",
    "userId" : "1234",
    "rating" : 5,
    "review" : "good quality milk",
    "image" : ""
}
###
POST     http://localhost:5000/api/subcategories/create
Content-Type: application/json

{
   "name" : "milk",
   "categoryName" : "dairy"
}  
