GET http://localhost:5000/api/categories


###
GET http://localhost:5000/products/200

###
POST http://localhost:5000/api/categories/create
Content-Type: application/json

{
    "categoryName":"Lifebuoy",
    "totalProducts":0,
    "categoryImage":"https://images-na.ssl-images-amazon.com/images/I/51qFv%2BsjCeL._SL1000_.jpg"
}