export { default as Navbar } from "./Navbar/Navbar";
export { default as Appbar } from "./Appbar/Appbar";
export { default as Product } from "./Product/Product";
export { default as About } from "./About/About";
export { default as Home } from "./Home/Home";
export { default as HorizontalSlider } from "./Slider/Slider";
export { default as Review} from "./Review/Review";
export { default as MultipleSlider} from "./MultipleSlider/MultipleSlider";
export { default as Category } from "./Category/Category";
export { default as Categories } from "./Categories/Categories";
export { default as CategorizedProduct} from "./CategorizedProduct/CategorizedProduct";